import { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { addDays, addMonths, eachDayOfInterval, endOfMonth, endOfWeek, format, isSameDay, isSameMonth, isWithinInterval, startOfMonth, startOfWeek, subMonths } from 'date-fns';
import { es } from 'date-fns/locale';
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, Clock3, Download, FileDown, History, Mountain, Pencil, Plus, Settings, Trash2, Upload, Users, X } from 'lucide-react';
import './styles.css';

type Worker={id:string;name:string;color:string;defaultHours:number}; type Assignment={id:string;workerId:string;date:string;workedHours:number}; type Data={workers:Worker[];assignments:Assignment[]};
const key='montrack-data', colors=['#0057FF','#3977EE','#71A1F5','#9ABEFF','#17449F','#5A85D8'];
const base:Data={workers:[{id:'w1',name:'María García',color:colors[0],defaultHours:8},{id:'w2',name:'Daniel Pérez',color:colors[1],defaultHours:7.5},{id:'w3',name:'Lucía Martín',color:colors[2],defaultHours:6}],assignments:[]};
const getData=()=>{try{return JSON.parse(localStorage.getItem(key)||'null')||base}catch{return base}}; const iso=(d:Date)=>format(d,'yyyy-MM-dd');

function App(){
 const [data,setData]=useState<Data>(getData),[tab,setTab]=useState<'calendar'|'history'|'workers'|'settings'>('calendar'),[cursor,setCursor]=useState(new Date()),[weekly,setWeekly]=useState(false),[day,setDay]=useState<Date|null>(null),[assign,setAssign]=useState<Worker|null>(null),[editing,setEditing]=useState<Worker|null|undefined>(undefined),[picker,setPicker]=useState(false),[toast,setToast]=useState(''); const importRef=useRef<HTMLInputElement>(null); const today=new Date();
 useEffect(()=>localStorage.setItem(key,JSON.stringify(data)),[data]); useEffect(()=>{if(toast){const t=setTimeout(()=>setToast(''),2300);return()=>clearTimeout(t)}},[toast]);
 const worker=(id:string)=>data.workers.find(w=>w.id===id); const onSaved=(message:string)=>setToast(message);
 const saveWorker=(name:string,hours:number)=>{if(editing?.id)setData(d=>({...d,workers:d.workers.map(w=>w.id===editing.id?{...w,name,defaultHours:hours}:w)}));else setData(d=>({...d,workers:[...d.workers,{id:crypto.randomUUID(),name,color:colors[d.workers.length%colors.length],defaultHours:hours}]}));setEditing(undefined);onSaved('Trabajador guardado')};
 const assignDays=(w:Worker,hours:number,dates:Date[],keep:boolean)=>{setData(d=>{const existing=new Set(d.assignments.filter(a=>a.workerId===w.id).map(a=>a.date));const extra=dates.filter(x=>!existing.has(iso(x))).map(date=>({id:crypto.randomUUID(),workerId:w.id,date:iso(date),workedHours:hours}));return {...d,workers:keep?d.workers.map(x=>x.id===w.id?{...x,defaultHours:hours}:x):d.workers,assignments:[...d.assignments,...extra]}});setAssign(null);onSaved('Jornadas asignadas')};
 return <main className="app"><header><div className="brand"><span><Mountain/></span><h1>Montrack</h1></div></header>
 {tab==='calendar'&&<Calendar data={data} cursor={cursor} weekly={weekly} setWeekly={setWeekly} setCursor={setCursor} openDay={setDay} openAssign={setAssign} openPicker={()=>setPicker(true)}/>}
 {tab==='history'&&<HistoryView data={data} worker={worker}/>} {tab==='workers'&&<Workers workers={data.workers} onEdit={setEditing} onDelete={id=>{if(confirm('¿Eliminar a este trabajador?')){setData(d=>({...d,workers:d.workers.filter(w=>w.id!==id)}));onSaved('Trabajador eliminado')}}} onAdd={()=>setEditing(null)}/>} {tab==='settings'&&<SettingsView data={data} importRef={importRef} onToast={onSaved} onImport={setData}/>} 
 <nav>{[["calendar",CalendarDays,'Calendario'],['history',History,'Historial'],['workers',Users,'Trabajadores'],['settings',Settings,'Ajustes']].map(([id,Icon,label])=>{const I=Icon as any;return <button key={id} className={tab===id?'active':''} onClick={()=>setTab(id as any)}><I/><span>{label as string}</span></button>})}</nav>
 {day&&<DayModal date={day} data={data} worker={worker} close={()=>setDay(null)} onAssign={()=>{setDay(null);}} onDelete={id=>{setData(d=>({...d,assignments:d.assignments.filter(a=>a.id!==id)}));onSaved('Jornada eliminada')}} onEditHours={(id,h)=>setData(d=>({...d,assignments:d.assignments.map(a=>a.id===id?{...a,workedHours:h}:a)}))} onPickWorker={()=>{setDay(null);setAssign(data.workers[0]||null)}}/>}
 {assign&&<AssignmentModal worker={assign} cursor={cursor} close={()=>setAssign(null)} onSave={assignDays}/>} {editing!==undefined&&<WorkerModal worker={editing||undefined} close={()=>setEditing(undefined)} onSave={saveWorker}/>} {picker&&<MonthPicker date={cursor} close={()=>setPicker(false)} onPick={d=>{setCursor(d);setPicker(false)}}/>} {toast&&<div className="toast"><Check/>{toast}</div>}</main>
}
function Calendar({data,cursor,weekly,setWeekly,setCursor,openDay,openAssign,openPicker}:any){const today=new Date();const start=weekly?startOfWeek(cursor,{weekStartsOn:1}):startOfWeek(startOfMonth(cursor),{weekStartsOn:1});const end=weekly?endOfWeek(cursor,{weekStartsOn:1}):endOfWeek(endOfMonth(cursor),{weekStartsOn:1});const days=eachDayOfInterval({start,end}); const assignments=(d:Date)=>data.assignments.filter((a:any)=>a.date===iso(d)); const w=(id:string)=>data.workers.find((x:any)=>x.id===id);const notCurrent=!isSameMonth(cursor,today)||cursor.getFullYear()!==today.getFullYear();
 return <section className="view"><div className="segmented"><button className={!weekly?'selected':''} onClick={()=>setWeekly(false)}>Mes</button><button className={weekly?'selected':''} onClick={()=>setWeekly(true)}>Semana</button></div><div className="month-nav"><button onClick={()=>setCursor(weekly?addDays(cursor,-7):subMonths(cursor,1))}><ChevronLeft/></button><button className="month-title" onClick={openPicker}>{format(cursor,'MMMM yyyy',{locale:es})}<ChevronDown/></button><button onClick={()=>setCursor(weekly?addDays(cursor,7):addMonths(cursor,1))}><ChevronRight/></button></div><div className="worker-chips">{data.workers.map((x:any)=><button key={x.id} onClick={()=>openAssign(x)}><i style={{background:x.color}}/>{x.name}<Plus/></button>)}{!data.workers.length&&<p>Añade trabajadores para registrar jornadas.</p>}</div><div className="calendar-card"><div className="week-labels">{['L','M','X','J','V','S','D'].map(x=><span key={x}>{x}</span>)}</div><div className="days">{days.map(d=><button key={d.toISOString()} onClick={()=>openDay(d)} className={'day '+(!isSameMonth(d,cursor)&&!weekly?'muted ':'')+(isSameDay(d,today)?'today':'')}><span>{format(d,'d')}</span><i>{assignments(d).slice(0,4).map((a:any)=><b key={a.id} style={{background:w(a.workerId)?.color}}/> )}</i></button>)}</div></div>{notCurrent&&<button className="back-today" onClick={()=>setCursor(today)}><Clock3/> Volver a hoy</button>}</section>}
function AssignmentModal({worker,cursor,close,onSave}:any){const [hours,setHours]=useState(worker.defaultHours),[keep,setKeep]=useState(false),[selected,setSelected]=useState<Date[]>([]);const days=eachDayOfInterval({start:startOfWeek(startOfMonth(cursor),{weekStartsOn:1}),end:endOfWeek(endOfMonth(cursor),{weekStartsOn:1})});const toggle=(d:Date)=>setSelected(s=>s.some(x=>isSameDay(x,d))?s.filter(x=>!isSameDay(x,d)):[...s,d]);return <Modal close={close} className="assignment-modal"><p className="eyebrow">ASIGNAR JORNADAS</p><div className="person-title"><i style={{background:worker.color}}/>{worker.name}</div><label>Horas trabajadas<input autoFocus type="number" min="0" step="0.25" value={hours} onChange={e=>setHours(+e.target.value)}/></label><label className="check"><input type="checkbox" checked={keep} onChange={e=>setKeep(e.target.checked)}/><span>Guardar como horas por defecto</span></label><p className="select-label">Selecciona los días</p><div className="mini-calendar"><div>{['L','M','X','J','V','S','D'].map(x=><span key={x}>{x}</span>)}</div><div>{days.map(d=><button key={d.toISOString()} onClick={()=>toggle(d)} className={(isSameMonth(d,cursor)?'':'muted ')+(selected.some(x=>isSameDay(x,d))?'picked':'')}>{format(d,'d')}</button>)}</div></div><button disabled={!selected.length} className="primary full" onClick={()=>onSave(worker,hours,selected,keep)}><Check/>Asignar a {selected.length||''} día{selected.length===1?'':'s'}</button></Modal>}
function DayModal({date,data,worker,close,onDelete,onEditHours,onPickWorker}:any){const a=data.assignments.filter((x:any)=>x.date===iso(date));return <Modal close={close}><p className="eyebrow">DETALLE DEL DÍA</p><h2>{format(date,"EEEE, d 'de' MMMM",{locale:es})}</h2><div className="assignment-list">{a.length?a.map((x:any)=><article className="assignment" key={x.id}><i style={{background:worker(x.workerId)?.color}}/><div><strong>{worker(x.workerId)?.name||'Trabajador eliminado'}</strong><input aria-label="Horas" type="number" step=".25" value={x.workedHours} onChange={e=>onEditHours(x.id,+e.target.value)}/><span>horas</span></div><button title="Eliminar" onClick={()=>onDelete(x.id)}><Trash2/></button></article>):<div className="empty"><Clock3/><p>No hay jornadas registradas.</p></div>}</div><button className="primary full" onClick={onPickWorker}><Plus/> Añadir trabajador</button></Modal>}
function Modal({children,close,className=''}:any){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className={'modal '+className}><button className="close" onClick={close}><X/></button>{children}</section></div>}
function WorkerModal({worker,close,onSave}:any){const [name,setName]=useState(worker?.name||''),[hours,setHours]=useState(worker?.defaultHours||8);return <Modal close={close}><p className="eyebrow">{worker?'EDITAR':'NUEVO'} TRABAJADOR</p><h2>{worker?'Actualizar trabajador':'Añadir trabajador'}</h2><label>Nombre<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Nombre completo"/></label><label>Horas por defecto<input type="number" step=".25" value={hours} onChange={e=>setHours(+e.target.value)}/></label><button className="primary full" disabled={!name.trim()} onClick={()=>onSave(name.trim(),hours)}><Check/>Guardar</button></Modal>}
function MonthPicker({date,close,onPick}:any){const [month,setMonth]=useState(date.getMonth()),[year,setYear]=useState(date.getFullYear());const months=Array.from({length:12},(_,x)=>format(new Date(2026,x,1),'MMMM',{locale:es}));return <Modal close={close} className="picker"><p className="eyebrow">IR A FECHA</p><h2>Mes y año</h2><div className="wheels"><select value={month} onChange={e=>setMonth(+e.target.value)}>{months.map((x,i)=><option value={i} key={x}>{x}</option>)}</select><select value={year} onChange={e=>setYear(+e.target.value)}>{Array.from({length:9},(_,i)=>date.getFullYear()-4+i).map(x=><option key={x}>{x}</option>)}</select></div><button className="primary full" onClick={()=>onPick(new Date(year,month,1))}>Ver calendario</button></Modal>}
function Workers({workers,onEdit,onDelete,onAdd}:any){return <section className="view"><div className="intro"><p>Gestiona tu equipo y sus horarios habituales.</p><button className="primary" onClick={onAdd}><Plus/>Nuevo</button></div><div className="workers-list">{workers.map((w:any)=><article className="worker" key={w.id}><i style={{background:w.color}}>{w.name[0]}</i><div><strong>{w.name}</strong><span>{w.defaultHours} h por defecto</span></div><button onClick={()=>onEdit(w)}><Pencil/></button><button onClick={()=>onDelete(w.id)}><Trash2/></button></article>)}</div></section>}
function HistoryView({data,worker}:any){const [range,setRange]=useState<'week'|'month'|'year'|'custom'>('month'),[from,setFrom]=useState(iso(startOfMonth(new Date()))),[to,setTo]=useState(iso(new Date())),[active,setActive]=useState<Worker|null>(null);const now=new Date();const interval=range==='week'?{start:startOfWeek(now,{weekStartsOn:1}),end:endOfWeek(now,{weekStartsOn:1})}:range==='month'?{start:startOfMonth(now),end:endOfMonth(now)}:range==='year'?{start:new Date(now.getFullYear(),0,1),end:new Date(now.getFullYear(),11,31)}:{start:new Date(from+'T00:00:00'),end:new Date(to+'T23:59:59')};const filtered=data.assignments.filter((a:any)=>isWithinInterval(new Date(a.date+'T12:00:00'),interval));const total=filtered.reduce((n:number,a:any)=>n+a.workedHours,0);return <section className="view"><div className="segmented history-segment">{[['week','Semana'],['month','Mes'],['year','Año'],['custom','Rango']].map(([id,label])=><button key={id} className={range===id?'selected':''} onClick={()=>setRange(id as any)}>{label}</button>)}</div>{range==='custom'&&<div className="range-inputs"><label>Desde<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>Hasta<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div>}<div className="stat-grid"><article><span>Horas trabajadas</span><strong>{total}<small> h</small></strong></article><article><span>Jornadas</span><strong>{filtered.length}</strong></article></div><h3>Trabajadores</h3><div className="history-list">{data.workers.map((w:any)=>{const a=filtered.filter((x:any)=>x.workerId===w.id),hours=a.reduce((n:number,x:any)=>n+x.workedHours,0);return <button key={w.id} onClick={()=>setActive(w)}><i style={{background:w.color}}/><div><strong>{w.name}</strong><span>{a.length} jornadas · {hours} h</span></div><ChevronRight/></button>})}</div>{active&&<HistoryModal worker={active} assignments={data.assignments.filter((a:any)=>a.workerId===active.id)} close={()=>setActive(null)}/>}</section>}
function HistoryModal({worker,assignments,close}:any){const now=new Date(), sum=(a:any[])=>a.reduce((n,x)=>n+x.workedHours,0),week=assignments.filter((a:any)=>isWithinInterval(new Date(a.date+'T12:00:00'),{start:startOfWeek(now,{weekStartsOn:1}),end:endOfWeek(now,{weekStartsOn:1})})),month=assignments.filter((a:any)=>isSameMonth(new Date(a.date+'T12:00:00'),now)),sorted=[...assignments].sort((a,b)=>b.date.localeCompare(a.date));return <Modal close={close} className="history-modal"><p className="eyebrow">HISTORIAL DE TRABAJADOR</p><div className="person-title"><i style={{background:worker.color}}/>{worker.name}</div><div className="metrics"><span>Total<h3>{sum(assignments)} h</h3></span><span>Jornadas<h3>{assignments.length}</h3></span><span>Promedio<h3>{assignments.length?(sum(assignments)/assignments.length).toFixed(1):0} h</h3></span><span>Esta semana<h3>{sum(week)} h</h3></span><span>Este mes<h3>{sum(month)} h</h3></span><span>Este año<h3>{sum(assignments.filter((a:any)=>new Date(a.date+'T12:00:00').getFullYear()===now.getFullYear()))} h</h3></span></div><p className="date-stats">Primera jornada: {sorted.length?format(new Date(sorted[sorted.length-1].date+'T12:00:00'),'dd/MM/yyyy'):'—'}<br/>Última jornada: {sorted.length?format(new Date(sorted[0].date+'T12:00:00'),'dd/MM/yyyy'):'—'}</p><h3>Registro cronológico</h3><div className="chronology">{sorted.length?sorted.map((a:any)=><div key={a.id}><span>{format(new Date(a.date+'T12:00:00'),'dd/MM/yyyy')}</span><b>{a.workedHours} h</b></div>):<p>Sin jornadas.</p>}</div></Modal>}
function SettingsView({data,importRef,onToast,onImport}:any){const bytes=new Blob([JSON.stringify(data)]).size;const read=(e:any)=>{const file=e.target.files?.[0];if(!file)return;const r=new FileReader();r.onload=()=>{try{onImport(JSON.parse(String(r.result)));onToast('Copia restaurada')}catch{onToast('El archivo no es válido')}};r.readAsText(file)};return <section className="view"><div className="storage"><div><span>Almacenamiento utilizado</span><strong>{(bytes/1024).toFixed(1)} KB <small>de 5 MB</small></strong></div></div><h3>Copias y exportación</h3><div className="settings-list"><button onClick={()=>backup(data,'json')}><Download/><span>Exportar copia<small>JSON · Formato restaurable</small></span><ChevronRight/></button><button onClick={()=>backup(data,'txt')}><FileDown/><span>Exportar TXT<small>Resumen legible para compartir</small></span><ChevronRight/></button><button onClick={()=>report(data)}><FileDown/><span>Exportar PDF<small>Informe imprimible</small></span><ChevronRight/></button><button onClick={()=>excel(data)}><FileDown/><span>Exportar Excel<small>Hoja de cálculo con jornadas</small></span><ChevronRight/></button><button onClick={()=>importRef.current?.click()}><Upload/><span>Importar copia<small>Restaurar desde JSON</small></span><ChevronRight/></button><input ref={importRef} type="file" accept="application/json" onChange={read}/></div><h3>Estado</h3><div className="info-list"><p><span>Meses exportados</span><b>0</b></p><p><span>Meses pendientes</span><b>0</b></p><p><span>Versión</span><b>1.1.0</b></p></div><h3>Acerca de Montrack</h3><p className="about">Montrack simplifica el registro diario de jornadas. Tus datos permanecen en este dispositivo.</p></section>}
function backup(data:Data,type:'json'|'txt'){let content='',mime='';if(type==='json'){content=JSON.stringify(data,null,2);mime='application/json'}else{content='MONTRACK — COPIA DE SEGURIDAD\n\nTRABAJADORES\n'+data.workers.map(w=>`• ${w.name} · ${w.defaultHours} h por defecto`).join('\n')+'\n\nJORNADAS\n'+data.assignments.map(a=>{const w=data.workers.find(x=>x.id===a.workerId);return `${a.date} · ${w?.name||'Trabajador eliminado'} · ${a.workedHours} h`}).join('\n');mime='text/plain'}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:mime}));a.download=`montrack-${format(new Date(),'yyyy-MM-dd')}.${type}`;a.click();URL.revokeObjectURL(a.href)}
function report(data:Data){const rows=data.assignments.map(a=>`<tr><td>${a.date}</td><td>${data.workers.find(w=>w.id===a.workerId)?.name||'—'}</td><td>${a.workedHours} h</td></tr>`).join('');const win=window.open('','_blank');if(!win)return;win.document.write(`<html><title>Informe Montrack</title><style>body{font:14px Arial;padding:35px;color:#192337}h1{color:#0057ff}table{width:100%;border-collapse:collapse;margin-top:25px}th,td{padding:10px;border-bottom:1px solid #ddd;text-align:left}</style><h1>Montrack</h1><p>Informe de jornadas · ${format(new Date(),'dd/MM/yyyy')}</p><table><thead><tr><th>Fecha</th><th>Trabajador</th><th>Horas</th></tr></thead><tbody>${rows}</tbody></table><script>print()</script></html>`);win.document.close()}
function excel(data:Data){const rows=data.assignments.map(a=>`<tr><td>${a.date}</td><td>${data.workers.find(w=>w.id===a.workerId)?.name||'—'}</td><td>${a.workedHours}</td></tr>`).join('');const content=`<table><thead><tr><th>Fecha</th><th>Trabajador</th><th>Horas</th></tr></thead><tbody>${rows}</tbody></table>`;const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type:'application/vnd.ms-excel'}));a.download=`montrack-informe-${format(new Date(),'yyyy-MM-dd')}.xls`;a.click();URL.revokeObjectURL(a.href)}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/sw.js');createRoot(document.getElementById('root')!).render(<App/>);
